{
  "stats": {
    "suites": 2,
    "tests": 6,
    "passes": 1,
    "pending": 0,
    "failures": 5,
    "start": "2023-03-10T22:59:52.413Z",
    "end": "2023-03-10T22:59:52.593Z",
    "duration": 180
  },
  "tests": [
    {
      "title": "has a folder named my-repository",
      "fullTitle": "this lab has a folder named my-repository",
      "duration": 13,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has a valid git repository initialized for the my-repository folder",
      "fullTitle": "this lab has a valid git repository initialized for the my-repository folder",
      "duration": 33,
      "currentRetry": 0,
      "err": {
        "message": "no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git",
        "stack": "AssertionError: no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:13:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git",
            "multiple": "AssertionError: no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist",
            "stack": "AssertionError: no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:13:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has a README.md file in the my-repository folder",
      "fullTitle": "this lab has a README.md file in the my-repository folder",
      "duration": 8,
      "currentRetry": 0,
      "err": {
        "message": "no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist",
        "showDiff": false,
        "actual": "./my-repository/README.md",
        "stack": "AssertionError: no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:17:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist",
            "showDiff": false,
            "actual": "./my-repository/README.md",
            "multiple": "AssertionError: no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist",
            "stack": "AssertionError: no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:17:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has README.md as a tracked file",
      "fullTitle": "the local repository has README.md as a tracked file",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "message": "no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git/index",
        "stack": "AssertionError: no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:25:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git/index",
            "multiple": "AssertionError: no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist",
            "stack": "AssertionError: no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:25:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has at least one commit",
      "fullTitle": "the local repository has at least one commit",
      "duration": 10,
      "currentRetry": 0,
      "err": {
        "message": "no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git/logs",
        "stack": "AssertionError: no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:29:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git/logs",
            "multiple": "AssertionError: no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist",
            "stack": "AssertionError: no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:29:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has been pushed up to the remote repository",
      "fullTitle": "the local repository has been pushed up to the remote repository",
      "duration": 9,
      "currentRetry": 0,
      "err": {
        "message": "no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git/logs/refs/remotes",
        "stack": "AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:33:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git/logs/refs/remotes",
            "multiple": "AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist",
            "stack": "AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:33:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    }
  ],
  "pending": [],
  "failures": [
    {
      "title": "has a valid git repository initialized for the my-repository folder",
      "fullTitle": "this lab has a valid git repository initialized for the my-repository folder",
      "duration": 33,
      "currentRetry": 0,
      "err": {
        "message": "no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git",
        "stack": "AssertionError: no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:13:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git",
            "multiple": "AssertionError: no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist",
            "stack": "AssertionError: no \".git\" folder was found within \"/my-repository, used \"git init\" to initialize: value: expected './my-repository/.git' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:13:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has a README.md file in the my-repository folder",
      "fullTitle": "this lab has a README.md file in the my-repository folder",
      "duration": 8,
      "currentRetry": 0,
      "err": {
        "message": "no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist",
        "showDiff": false,
        "actual": "./my-repository/README.md",
        "stack": "AssertionError: no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:17:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist",
            "showDiff": false,
            "actual": "./my-repository/README.md",
            "multiple": "AssertionError: no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist",
            "stack": "AssertionError: no README.md file found within \"/my-repository\": expected './my-repository/README.md' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:17:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has README.md as a tracked file",
      "fullTitle": "the local repository has README.md as a tracked file",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "message": "no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git/index",
        "stack": "AssertionError: no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:25:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git/index",
            "multiple": "AssertionError: no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist",
            "stack": "AssertionError: no files are being tracked.  Use \"git add .\" to track all files in this repo: expected './my-repository/.git/index' to exist\n    at assert.pathExists (node_modules/chai-fs/lib/assertions/path.js:31:35)\n    at Context.<anonymous> (test/index-test.js:25:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has at least one commit",
      "fullTitle": "the local repository has at least one commit",
      "duration": 10,
      "currentRetry": 0,
      "err": {
        "message": "no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git/logs",
        "stack": "AssertionError: no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:29:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git/logs",
            "multiple": "AssertionError: no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist",
            "stack": "AssertionError: no commits were found.  Use \"git commit -m\" followed by a message to create a commit: value: expected './my-repository/.git/logs' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:29:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    },
    {
      "title": "has been pushed up to the remote repository",
      "fullTitle": "the local repository has been pushed up to the remote repository",
      "duration": 9,
      "currentRetry": 0,
      "err": {
        "message": "no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist",
        "showDiff": false,
        "actual": "./my-repository/.git/logs/refs/remotes",
        "stack": "AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:33:17)\n    at process.processImmediate (node:internal/timers:475:21)",
        "multiple": [
          {
            "name": "AssertionError",
            "message": "no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist",
            "showDiff": false,
            "actual": "./my-repository/.git/logs/refs/remotes",
            "multiple": "AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist",
            "stack": "AssertionError: no record of pushing to a remote was found. Follow the instructions on GitHub to connect and push to a new remote repository: value: expected './my-repository/.git/logs/refs/remotes' to exist\n    at Function.<anonymous> (node_modules/chai-fs/lib/assertions/directory.js:21:53)\n    at ctx.<computed> [as directory] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)\n    at assert.isDirectory (node_modules/chai-fs/lib/assertions/directory.js:34:35)\n    at Context.<anonymous> (test/index-test.js:33:17)\n    at process.processImmediate (node:internal/timers:475:21)"
          }
        ]
      }
    }
  ],
  "passes": [
    {
      "title": "has a folder named my-repository",
      "fullTitle": "this lab has a folder named my-repository",
      "duration": 13,
      "currentRetry": 0,
      "err": {}
    }
  ]
}